global using CasCap.Common.Extensions;
global using CasCap.HealthChecks;
global using CasCap.Models;
global using CasCap.Services;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Xunit;
global using Xunit.Abstractions;
