{{- define "workload.scaledobject" -}}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "workload.fullname" . }}
  namespace: {{ include "workload.namespace" $ }}
  labels:
    {{- include "workload.labels" . | nindent 4 }}
{{- range $key, $val := .Values.labels }}
    {{ $key }}: {{ $val | quote }}
{{- end}}
spec:
  scaleTargetRef:
    #apiVersion:    {api-version-of-target-resource} # Optional. Default: apps/v1
    #kind:          {kind-of-target-resource}        # Optional. Default: Deployment
    name:           {{ .Chart.Name }}                # Mandatory. Must be in the same namespace as the ScaledObject
    #envSourceContainerName: {container-name}        # Optional. Default: .spec.template.spec.containers[0]
  pollingInterval: 10                                # Optional. Default: 30 seconds
  cooldownPeriod:  300                               # Optional. Default: 300 seconds
  minReplicaCount: 1                                 # Optional. Default: 0
  maxReplicaCount: 2                                 # Optional. Default: 100
  # advanced:                                          # Optional. Section to specify advanced options
  #   restoreToOriginalReplicaCount: true/false        # Optional. Default: false
  #   horizontalPodAutoscalerConfig:                   # Optional. Section to specify HPA related options
  #     behavior:                                      # Optional. Use to modify HPA's scaling behavior
  #       scaleDown:
  #         stabilizationWindowSeconds: 300
  #         policies:
  #         - type: Percent
  #           value: 100
  #           periodSeconds: 15
  triggers:
  - type: azure-queue
    metadata:
      queueName: app{{ .Chart.Name }}
      queueLength: '5' # Optional. Queue length target for HPA. Default: 5 messages
    # Required: connection OR authenticationRef that defines connection or authenticationRef as defined below
    # connection: STORAGE_CONNECTIONSTRING_ENV_NAME # Default: AzureWebJobsStorage. Reference to a connection string in deployment
    authenticationRef:
      name: {{ include "workload.fullname" . }}-queue-auth # authenticationRef would need either podIdentity or define a connection parameter
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ include "workload.fullname" . }}-queue-auth
  namespace: {{ include "workload.namespace" $ }}
  labels:
    {{- include "workload.labels" . | nindent 4 }}
spec:
  secretTargetRef:
  - parameter: connection
    name: cc-storage-app-{{ .Chart.Name }}-secret
    key: CONNECTIONSTRINGS__APP{{ upper .Chart.Name }}
{{- end }}