{{- define "workload.scaledjob" -}}
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: {{ include "workload.fullname" . }}
  namespace: {{ include "workload.namespace" $ }}
  labels:
    {{- include "workload.labels" . | nindent 4 }}
{{- range $key, $val := .Values.labels }}
    {{ $key }}: {{ $val | quote }}
{{- end}}
spec:
  jobTargetRef:
    parallelism: 1                            # [max number of desired pods](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#controlling-parallelism)
    completions: 1                            # [desired number of successfully finished pods](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#controlling-parallelism)
    activeDeadlineSeconds: 600                #  Specifies the duration in seconds relative to the startTime that the job may be active before the system tries to terminate it; value must be positive integer
    backoffLimit: 6                           # Specifies the number of retries before marking this job failed. Defaults to 6
    template:
      metadata:
        {{- with .Values.podAnnotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        labels:
          {{- include "workload.labels" . | nindent 10 }}
          {{- with .Values.podLabels }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
      spec:
        restartPolicy: {{ default "Never" .Values.restartPolicy }}
        runtimeClassName: {{ default "" .Values.runtimeClassName }}
        {{- with .Values.imagePullSecrets }}
        imagePullSecrets:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.serviceAccount }}
        serviceAccountName: {{ .Values.serviceAccount.name | quote }}
        {{- end }}
        {{- if and (hasKey .Values "podSecurityContext") (.Values.podSecurityContext) }}
        securityContext:
          {{- toYaml .Values.podSecurityContext | nindent 10 }}
        {{- end }}
        containers:
        - name: {{ .Chart.Name }}
          {{- if and (hasKey .Values "securityContext") (.Values.securityContext) }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy }}
          {{- with .Values.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- include "workload.probes" . | trim | nindent 10 }}
          env:
            - name: AppConfig__NodeName
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: AppConfig__PodName
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: AppConfig__Namespace
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: AppConfig__PodIp
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: AppConfig__ServiceAccountName
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            {{- range $key, $value := $.Values.envVars }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $secret := $.Values.envSecrets }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secret }}
                  key: {{ $key | quote }}
            {{- end }}
          {{- if and (hasKey .Values "envVarsFrom") (.Values.envVarsFrom) }}
          envFrom:
            {{- toYaml .Values.envVarsFrom | nindent 12 }}
          {{- end }}
{{- if and (hasKey .Values "resources") (.Values.resources) }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- with .Values.volumes }}
        volumes:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.nodeSelector }}
        nodeSelector:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.affinity }}
        affinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.tolerations }}
        tolerations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
    backoffLimit: 4
  pollingInterval: 10                         # Optional. Default: 30 seconds
  successfulJobsHistoryLimit: 5               # Optional. Default: 100. How many completed jobs should be kept.
  failedJobsHistoryLimit: 5                   # Optional. Default: 100. How many failed jobs should be kept.
  #envSourceContainerName: {container-name}    # Optional. Default: .spec.JobTargetRef.template.spec.containers[0]
  maxReplicaCount: 100                        # Optional. Default: 100
  rolloutStrategy: gradual                    # Optional. Default: default. Which Rollout Strategy KEDA will use.
  # scalingStrategy:
  #   strategy: "custom"                        # Optional. Default: default. Which Scaling Strategy to use. 
  #   customScalingQueueLengthDeduction: 1      # Optional. A parameter to optimize custom ScalingStrategy.
  #   customScalingRunningJobPercentage: "0.5"  # Optional. A parameter to optimize custom ScalingStrategy.
  #   pendingPodConditions:                     # Optional. A parameter to calculate pending job count per the specified pod conditions
  #     - "Ready"
  #     - "PodScheduled"
  #     - "AnyOtherCustomPodCondition"
  #   multipleScalersCalculation : "max" # Optional. Default: max. Specifies how to calculate the target metrics when multiple scalers are defined.
  triggers:
  - type: azure-queue
    metadata:
      queueName: app{{ .Chart.Name }}
      queueLength: '5' # Optional. Queue length target for HPA. Default: 5 messages
    # Required: connection OR authenticationRef that defines connection or authenticationRef as defined below
    # connection: STORAGE_CONNECTIONSTRING_ENV_NAME # Default: AzureWebJobsStorage. Reference to a connection string in deployment
    authenticationRef:
      name: {{ include "workload.fullname" . }}-queue-auth # authenticationRef would need either podIdentity or define a connection parameter
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ include "workload.fullname" . }}-queue-auth
  namespace: {{ include "workload.namespace" $ }}
  labels:
    {{- include "workload.labels" . | nindent 4 }}
spec:
  secretTargetRef:
  - parameter: connection
    name: cc-storage-app-{{ .Chart.Name }}-secret
    key: CONNECTIONSTRINGS__APP{{ upper .Chart.Name }}
{{- end }}