{{- if eq (default "Deployment" .Values.kind) "CronJob" }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "workload.fullname" . }}
  namespace: {{ include "workload.namespace" $ }}
  labels:
    {{- include "workload.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronJobSchedule | quote }}
  concurrencyPolicy: {{ default "Replace" .Values.cronJobConcurrencyPolicy }}
  jobTemplate:
    spec:
      template:
        metadata:
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          labels:
            {{- include "workload.labels" . | nindent 12 }}
            {{- with .Values.podLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          restartPolicy: {{ default "Never" .Values.restartPolicy }}
          {{- with .Values.runtimeClassName }}
          runtimeClassName: {{ . }}
          {{- end }}
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.serviceAccount }}
          serviceAccountName: {{ .Values.serviceAccount.name | quote }}
          {{- end }}
          {{- if and (hasKey .Values "podSecurityContext") (.Values.podSecurityContext) }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          {{- end }}
          {{- with .Values.initContainers }}
          initContainers:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
          - name: {{ .Chart.Name }}
            {{- if and (hasKey .Values "securityContext") (.Values.securityContext) }}
            securityContext:
              {{- toYaml .Values.securityContext | nindent 14 }}
            {{- end }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy }}
            {{- with .Values.command }}
            command:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with .Values.args }}
            args:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            env:
              {{- range $name, $fieldPath := $.Values.envFieldRef }}
              - name: {{ $name }}
                valueFrom:
                  fieldRef:
                    fieldPath: {{ $fieldPath }}
              {{- end }}
              {{- range $key, $value := $.Values.envVars }}
              - name: {{ $key }}
                value: {{ $value | quote }}
              {{- end }}
              {{- range $key, $secret := $.Values.envSecrets }}
              - name: {{ $key }}
                valueFrom:
                  secretKeyRef:
                    name: {{ $secret }}
                    key: {{ $key | quote }}
              {{- end }}
            {{- if and (hasKey .Values "envVarsFrom") (.Values.envVarsFrom) }}
            envFrom:
              {{- toYaml .Values.envVarsFrom | nindent 14 }}
            {{- end }}
            {{- if and (hasKey .Values "resources") (.Values.resources) }}
            resources:
              {{- toYaml .Values.resources | nindent 14 }}
            {{- end }}
            {{- with .Values.volumeMounts }}
            volumeMounts:
              {{- toYaml . | nindent 14 }}
            {{- end }}
          {{- with .Values.volumes }}
          volumes:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
