namespace CasCap.Models.Dtos;

/// <summary>
/// Site-level power flow summary returned inside <see cref="PowerFlowRealtimeData"/>.
/// </summary>
public record PowerFlowSite
{
    /// <summary>
    /// Whether backup mode is active.
    /// </summary>
    [Description("Whether backup mode is active.")]
    public bool BackupMode { get; init; }

    /// <summary>
    /// Whether the battery is in standby.
    /// </summary>
    [Description("Whether the battery is in standby.")]
    public bool BatteryStandby { get; init; }

    /// <summary>
    /// Energy generated today in watt-hours.
    /// </summary>
    [Description("Energy generated today in watt-hours.")]
    public double? E_Day { get; init; }

    /// <summary>
    /// Total energy generated over the lifetime of the system in watt-hours.
    /// </summary>
    [Description("Total energy generated over the lifetime of the system in watt-hours.")]
    public double E_Total { get; init; }

    /// <summary>
    /// Energy generated this year in watt-hours.
    /// </summary>
    [Description("Energy generated this year in watt-hours.")]
    public double? E_Year { get; init; }

    /// <summary>
    /// Meter location (e.g. "grid").
    /// </summary>
    [Description("Meter location (e.g. \"grid\").")]
    public string? Meter_Location { get; init; }

    /// <summary>
    /// Operating mode (e.g. "meter", "vague-meter", "bidirectional").
    /// </summary>
    [Description("Operating mode (e.g. \"meter\", \"vague-meter\", \"bidirectional\").")]
    public string? Mode { get; init; }

    /// <summary>
    /// Power from battery in watts (positive = discharging, negative = charging).
    /// </summary>
    [Description("Power from battery in watts (positive = discharging, negative = charging).")]
    public double P_Akku { get; init; }

    /// <summary>
    /// Power from grid in watts (positive = consuming, negative = feeding).
    /// </summary>
    [Description("Power from grid in watts (positive = consuming, negative = feeding).")]
    public double P_Grid { get; init; }

    /// <summary>
    /// Power consumption (load) in watts (always negative).
    /// </summary>
    [Description("Power consumption (load) in watts (always negative).")]
    public double P_Load { get; init; }

    /// <summary>
    /// Power generated by PV in watts.
    /// </summary>
    [Description("Power generated by PV in watts.")]
    public double P_PV { get; init; }

    /// <summary>
    /// Relative autonomy as a percentage (0–100).
    /// </summary>
    [Description("Relative autonomy as a percentage (0–100).")]
    public double rel_Autonomy { get; init; }

    /// <summary>
    /// Relative self-consumption as a percentage (0–100), or null when PV power is zero.
    /// </summary>
    [Description("Relative self-consumption as a percentage (0–100), or null when PV power is zero.")]
    public double? rel_SelfConsumption { get; init; }
}
