# Disable AOF https://redis.io/topics/persistence#append-only-file
appendonly no

#Disable RDB snapshotting by commenting all of the save configuration directives (there are 3 that are defined by default)
# save 900 1
# save 300 10
# save 60 10000
# #save 5 1 #force save every 5 seconds if 1 or more changes were detected
save ""

# Turn on certain keyspace events
#https://stackoverflow.com/questions/23180765/redis-keyspace-notifications-with-stackexchange-redis
#https://redis.io/topics/notifications
#notify-keyspace-events KEs #set
#notify-keyspace-events KEh
#notify-keyspace-events KEx #expirations
notify-keyspace-events KEhx
